spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gyeol
    username: hongmunil
    password: Child4564!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "m4NZGxaYH2kR2+QdU9artLinlrZqxb9BL9kHNfKOwvt/ZlYDCw3aH+0ZgTgjRE0wVSok3xWi5tCZ04hCeU78NA=="
  access-token-validity-ms: 3600000   # 60분 (나중에 필요시 조정)