spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gyeol
    username: hongmunil
    password: Child4564!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect